app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get("test_queue/{id}",array("uses"=>"TestController@sendReminderEmail"));
//Route::get("local_testing",array("uses"=>"TestController@local_testing"));
//Route::get("just_test",array("uses"=>"TestController@just_test"));
//Route::get("test_multiple_tables",array("uses"=>"TestController@test_multiple_tables"));
Route::get("test_fetch_products",array("uses"=>"TestController@test_fetch_products"));
//Route::get('test_fetch_products',array("uses"=>"TestController@test_fetch_products"));

Route::get("testing",array("uses"=>"TestController@testing"));
Route::get("test-compose-message",array("uses"=>"TestController@test_compose_message"));


Route::match(array("GET","POST"),"user/login",array('uses'=>'UserController@login'));
Route::get("enqueue-fetch-orders",array("uses"=>"JobsController@enqueueFetchOrderJob"));
Route::get("enqueue-send-emails",array("uses"=>"JobsController@enqueueSendEmailsJob"));
Route::get("enqueue-fetch-products",array("uses"=>"JobsController@enqueueFetchProductsJob"));
Route::get("enqueue-fetch-feedbacks",array("uses"=>"JobsController@enqueueFetchFeedbacks"));
Route::get("enqueue-fetch-reviews",array("uses"=>"JobsController@enqueueFetchReviewsAndRatings"));
Route::get("request-orders-reports",array("uses"=>"JobsController@requestOrdersReports"));
Route::get("unsubscribe/{email}",'BlacklistEmailController@unsubscribe');
Route::get("general-message",'BlacklistEmailController@general_message');

//  Route::get("test_feedback",array("uses"=>"TestController@test_feedback"));
//  Route::get("test_brands",array("uses"=>"TestController@assignBrands"));
//Route::get("test_reviews",array("uses"=>"TestController@test_reviews"));





/*
|--------------------------------------------------------------------------
| Basic Authenticated Routes
|--------------------------------------------------------------------------
*/









Route::group(array("middleware"=>'logged_in'),function(){
//

    Route::get("user/choose-setting/{id}",array('uses'=>'UserController@chooseDefaultSetting'));
    Route::get("user/logout",array("uses"=>'UserController@logout'));

    Route::group(array("prefix"=>'opportunityfinder'),function(){
        Route::get('/', array('as'=>'opportunityfinder','uses' => 'OpportunityController@index'));
        Route::match(array('get', 'post'),"find_opportunity",array("as"=>'find_opportunity','uses'=>'OpportunityController@findOpportunity'));
        Route::get("opportunity_ajax",array("as"=>'opportunity_ajax','uses'=>'OpportunityController@opportunityAjax'));
        Route::get("opportunity_cron",array("as"=>'opportunity_cron','uses'=>'OpportunityController@opportunityCron'));
        Route::get("make_asin",array("as"=>'make_asin','uses'=>'OpportunityController@makeAsin'));
        Route::get("populate_products",array("as"=>'populate_products','uses'=>'OpportunityController@populateProducts'));
        Route::get("populate_general_products",array("as"=>'populate_general_products','uses'=>'OpportunityController@populateGeneralProducts'));
        Route::get("get_review_rating",array("as"=>'get_review_rating','uses'=>'OpportunityController@getReviewRating'));
        Route::get("set_price",array("as"=>'set_price','uses'=>'OpportunityController@gePrice'));
        Route::get("saved-search",array('uses'=>'OpportunityController@savedSearch'));
        Route::get("remove_saved_search",array('uses'=>'OpportunityController@removeSavedSearch'));
        Route::match(array('get', 'post'),"scrap_top_sellers",array("as"=>'scrap_top_sellers','uses'=>'OpportunityController@scrap_top_sellers'));
        Route::match(array('get', 'post'),"del_pro",array("as"=>'del_pro','uses'=>'OpportunityController@del_pro'));
    });

    Route::group(array("middleware"=>'check_user_settings'),function()
    {

        Route::get("orders",array("as"=>'orders','uses'=>'BrandController@orders'));

        Route::get("products",array("as"=>"products","uses"=>"UserController@products"));
        Route::get('/',array("uses"=>"UserController@index"));
        Route::resource("brands",'BrandController');
        Route::match(array("GET","POST"),"messages/settings",array("as"=>'settings','uses'=>'MessageController@saveSetting'));
        Route::get("messages/sent",array("as"=>'settings','uses'=>'MessageController@sent'));
        Route::get("messages/outbox",array("as"=>'outbox','uses'=>'MessageController@outbox'));
        Route::get("messages/outbox/delete/{id}",array('uses'=>'MessageController@deleteOutbox'));


        Route::resource("messages",'MessageController');
        Route::resource("variables",'VariableController');
        Route::resource("blacklist-emails",'BlacklistEmailController');


        Route::get("brand-data/{setting_id}",array("uses"=>"BrandController@getBrandData"));
        Route::get("assign-brand",array("uses"=>"BrandController@assignBrands"));
        Route::post("save-brand-assignment",array("uses"=>"BrandController@saveBrandAssignment"));
        Route::match(array("GET","POST"),"product-data",array('as'=>'product-data','uses'=>'BrandController@getProductData'));
        Route::get("feedbacks",array('as'=>'feedbacks','uses'=>'FeedbackController@index'));
        Route::get("feedback-detail/{feedback}",array("as"=>"feedback-detail","uses"=>"FeedbackController@show"));
        Route::match(array("GET","POST"),"feedbacks-data",array('as'=>'feedbacks-data','uses'=>'FeedbackController@getData'));
        Route::post("feedbacks/update/{feedback}",array('as'=>'feedbacks/update','uses'=>'FeedbackController@update'));

        Route::get("track-product",array("as"=>"track-product","uses"=>"BrandController@trackProduct"));
        Route::post("track-product",array("as"=>"track-product","uses"=>"BrandController@trackAndSaveProduct"));
        Route::get("list-brand-data",array("uses"=>"BrandController@getListBrandData"));
        Route::get("list-order-data",array("uses"=>"BrandController@getListOrderData"));
        Route::get("report_testing",array("uses"=>"TestController@report_testing"));
        Route::get("report_list_testing",array("uses"=>"TestController@report_list_testing"));
        Route::get("get_report_testing",array("uses"=>"TestController@get_report_testing"));





        /*
        |--------------------------------------------------------------------------
        | User Routes
        |--------------------------------------------------------------------------
        */
        Route::group(array("prefix"=>"user"),function(){

            Route::get("dashboard",array('uses'=>'UserController@index'));
            Route::get("rating-data",array("as"=>"rating-data","uses"=>"UserController@getProductData"));

            /*
             *  User MarketPlace Setting routes
             */
            Route::get("add-marketplace-setting",array('uses'=>'UserController@saveMarketplaceSetting'));
            Route::get("edit-marketplace-setting/{id}",array('uses'=>'UserController@saveMarketplaceSetting'));
            Route::post("save-marketplace-setting",array('uses'=>'UserController@saveMarketplaceSetting'));
            Route::get("marketplace-settings",array('uses'=>'UserController@marketplaceSettings'));
            Route::get("delete-marketplace-setting/{id}",array('uses'=>'UserController@deleteMarketplaceSetting'));
            /*
             *  User Product Advertising Setting routes
             */
            Route::get("add-aws-setting",array('uses'=>'UserController@saveProdAdvSetting'));
            Route::get("edit-aws-setting/{id}",array('uses'=>'UserController@saveProdAdvSetting'));
            Route::post("save-product-advertising-setting",array('uses'=>'UserController@saveProdAdvSetting'));
            Route::get("aws-settings",array('uses'=>'UserController@prodAdvSettings'));
            Route::get("delete-product-advertising-setting/{id}",array('uses'=>'UserController@deleteProdAdvSetting'));
        });




    });



});

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\AmazonProduct;
use App\UserAmazonSetting;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Requests\BrandRequest;
use View;
use App\Brand;
use Session;
use Illuminate\Support\Facades\Redirect;
use App\Marketplace;
use App\AmazonOrder;

class BrandController extends Controller
{
    private static $marketplace_settings;
    private $user;
    public function __construct()
    {

        $this->user = Session::get("user");

        self::$marketplace_settings =   array();
        $marketplace_settings = UserAmazonSetting::where(array("profile_id" => $this->user['profile_id'], "setting_type" => "marketplace"))
            ->select(\DB::raw("concat(account_name,'(',seller_id,')'), id"))
            ->get();
        if($marketplace_settings)
        {
            $marketplace_settings=$marketplace_settings->toArray();
            if(!empty($marketplace_settings))
            {
                foreach($marketplace_settings as $settings)
                {
                    self::$marketplace_settings [$settings['id']]   =   $settings["concat(account_name,'(',seller_id,')')"];
                }
            }
        }
    }
    public function index()
    {
        $setting_str    =   self::build_setting_str(TRUE);
        return View::make("brands.index", compact("setting_str"));
    }
    public function getListBrandData(Request $request)
    {
        try
        {
            $response = array();
            $params = $request->input();
            $user = Session::get('user');

            $brands = Brand::getBrandsBySetting($params);

            $response['recordsTotal'] = $brands['total'];
            unset($brands['total']);

            $response['recordsFiltered'] = $brands['filtered'];
            unset($brands['filtered']);


            $response['draw'] = $params['draw'];

            $response['data'] = $brands;

        }
        catch(Exception $exp)
        {
            echo $exp->getMessage();exit;
        }
        return json_encode($response,true);
    }
    public function create()
    {
        return View::make("brands.form",array("marketplace_settings"=>self::$marketplace_settings));
    }
    public function store(BrandRequest $request)
    {

        $data = \Input::all();
        $user = Session::get("user");
        $data['profile_id'] = $user['profile_id'];
        $result = Brand::saveToDb($data);

        if ($result['status'] == '1')
        {
            if(isset($data['save_add']))
                return Redirect::route('brands.create')->with('success_message', $result['message']);
            else
                return Redirect::route('brands.index')->with('success_message', $result['message']);
        }
        else if ($result['status'] == '3')
        {
            return Redirect::route('brands.index')->with('error_message',$result['message']);

        }

    }
    public function show($id)
    {
        echo "show method";
        //
    }
    public function edit(BrandRequest $request,Brand $brand)
    {
       return View::make("brands.form")->with(array("brand"=>$brand,"marketplace_settings"=>self::$marketplace_settings));
    }
    public function update(BrandRequest $request, Brand $brand)
    {
        $data   =    \Input::all();
        $data ['profile_id']  =     Session::get("user")['profile_id'];
        $result = Brand::saveToDb($data);
        if ($result['status'] == '1')
        {
            if(isset($data['save_add']))
                return Redirect::route('brands.create')->with('success_message', $result['message']);
            else
                return Redirect::route('brands.index')->with('success_message', $result['message']);
        }
        else if ($result['status'] == '3')
        {
            return Redirect::route('brands.index')->with('error_message',$result['message']);

        }
    }
    public function destroy(BrandRequest $request, Brand $brand)
    {
        $is_deleted =   Brand::deleteBrand($brand);
        if ($is_deleted)
        {
            $brand    ="Brand deleted from the system";
            Session::flash("success_message",$brand);
        }
        else
        {
            $brand    ="Brand could not be deleted";
            Session::flash("error_message",$brand);
        }
        return url("brands");
    }
    private static function build_setting_str($already_populated="",array $settings=array())
    {
        $setting_str        =   "";
        if(!empty($already_populated))
        {
            $settings   =   self::$marketplace_settings;
            if(!empty($settings))
            {
                foreach ($settings as $key => $setting)
                {
                    $setting_str .= "'" . $key . ":::" . $setting . "',";
                }
            }
        }
        else
        {
            foreach ($settings as $setting)
            {
                $setting_str .= "'" . $setting['id'] . ":::" . $setting['account_name'] . " (" . $setting['seller_id'] . ")',";
            }
        }
        if(!empty($setting_str))
            $setting_str        =   substr($setting_str,0,-1);
        return $setting_str;
    }
    private static function build_brand_str(array $brands)
    {
        $brands_str         =   "";
        foreach($brands as $brand)
        {
            $brands_str   .=  "'".$brand['id'].":::".$brand['name']."',";
        }
        if(!empty($brands_str))
            $brands_str         =   substr($brands_str,0,-1);
        return $brands_str;
    }
    public function assignBrands()
    {
        $brands         =   Brand::getBrands("","",TRUE);
        $setting_str    =   self::build_setting_str(TRUE);
        $brands_str       =   self::build_brand_str($brands);
        return View::make("brands.brand_assignment", compact("setting_str","brands_str"));
    }
    public function getProductData(Request $request)
    {
        try
        {
            $response = array();
            $params = $request->input();
            $user = Session::get('user');

            $products = AmazonProduct::getProductsBySetting(TRUE,$params);

            $response['recordsTotal'] = $products['total'];
            unset($products['total']);

            $response['recordsFiltered'] = $products['filtered'];
            unset($products['filtered']);


            $response['draw'] = $params['draw'];

            $response['data'] = $products;

        }
        catch(Exception $exp)
        {
            echo $exp->getMessage();exit;
        }
        return json_encode($response,true);
    }
    public function getBrandData($setting_id)
    {
        $brands =   Brand::where(array("setting_id"=>$setting_id))
               ->select(["id","name"])
               ->get();
        if(!$brands->isEmpty())
            $brands =   $brands->toArray();
        else
            $brands =   array();
        return $brands;
    }
    public function saveBrandAssignment(Request $request)
    {
        $data   =   $request->input();

        $user = Session::get("user");
        $data['profile_id'] = $user['profile_id'];
        $result = Brand::assignBrandsToProducts($data);

        if ($result['status'] == '1')
        {
            return redirect('assign-brand')->with('success_message', $result['message']);
        }
        else if ($result['status'] == '3')
        {
            return redirect('assign-brand')->with('error_message',$result['message']);

        }

    }
    public function trackProduct()
    {
        return View::make("brands.products_traking_form",array("marketplace_settings"=>self::$marketplace_settings));
    }
    public function trackAndSaveProduct()
    {
        $data   =  \Input::all();

        $user = Session::get("user");
        $data['profile_id'] = $user['profile_id'];
        $result = AmazonProduct::trackProduct($data);

        if ($result['status'] == '1')
        {
            return redirect('track-product')->with('success_message', $result['message']);
        }
        else if ($result['status'] == '3')
        {
            return redirect('track-product')->with('error_message',$result['message']);

        }
        else
        {
            return redirect('track-product')->with('error_message'," Error in system. Please try again later");

        }
    }
    public function orders()
    {
        $setting_str    =   self::build_setting_str(TRUE);
        return View::make("messages.orders", compact("setting_str"));
    }
    public function getListOrderData(Request $request)
    {
        try
        {
            $response = array();
            $params = $request->input();
            $user = Session::get('user');

            $orders =   AmazonOrder::getOrdersBySetting($params);
            $response['recordsTotal'] = $orders['total'];
            unset($orders['total']);

            $response['recordsFiltered'] = $orders['filtered'];
            unset($orders['filtered']);


            $response['draw'] = $params['draw'];

            $response['data'] = $orders;

        }
        catch(Exception $exp)
        {
            echo $exp->getMessage();exit;
        }
        return json_encode($response,true);
    }
}

resources/views/brands/brand_assignment.blade.php
@extends('main_template')

@section ("title")

    Assign Brand to Products

@stop

@section("right_header")

    <div class="col-sm-6" xmlns="http://www.w3.org/1999/html">

        <div class="add_link">

            <a href="<?php echo url('track-product'); ?>"><span class="fa fa-plus"></span> Add Product</a>

        </div>

    </div>

@stop

@section("content")



    <form action="{!! url('save-brand-assignment') !!}" class="bs-example form-inline" method="post" enctype="multipart/form-data" id="productform"  data-validate="parsley" >

        <div class="wrapper-inline-form">

            <div class="row">

                <div class="col-md-12">

                    {!! csrf_field() !!}

                    <div class="form-group">

                        <?php /*   <label class="col-lg-4 control-label">Market Place :</label> */ ?>



                    </div>



                    <div class="form-group">

                        <div  name="marketplace_select" id="marketplace_select">



                        </div>

                    </div>

                    <div class="form-group">

                        <div  name="brand_select" id="brand_select">



                        </div>

                    </div>

                    <div class="form-group">

                        <?php /*      <label class="col-lg-4 control-label">Status :</label> */ ?>



                    </div>

                </div>

            </div>

        </div>

        <div class="row">

            <div class="col-md-12">

                <div class="table-responsive">

                    <table class="table table-bordered table-striped" data-ride="datatables" id="server_sisde_dtable">

                        <thead>

                        <tr bgcolor="#f4f4f4">

                            <th width="10%">Sr</th>

                            <th width="20%">ASIN</th>

                            <th width="60%">Product Name </th>

                            <th width="10%">Action</th>

                        </tr>

                        </thead>

                        <tbody>

                        </tbody>

                    </table>

                </div>

            </div>

        </div>

        <div class="row">

            <div class="row">

                <div class="col-md-12 text-center button-top">

                    {!! Form::submit('Assign', ['id' => 'savedata','name' => 'save','class' => 'btn btn-primary']) !!}

                </div>

            </div>

        </div>



    </form>

@stop

@section('additional_js')

    <script>

        $(function() {

            var table   =   $('#server_sisde_dtable').DataTable( {

                "processing": true,

                "serverSide": true,

                "ajax": "<?php echo url("product-data"); ?>",

                'drawCallback':function() {

                    var old_setting     =   "";



                    var setting_select = $("#marketplace_select_filter");

                    var brand_select = $("#brand_select_filter");

                    var setting_id  =   $(setting_select).val();

                    var brand_id  =   $(brand_select).val();

                    if(typeof setting_select !="undefined" && typeof brand_select !="undefined")

                    {

                        old_setting=setting_id;

                        var options =   $(brand_select).find("option");

                        $(options).slice(1).remove();

                        $.ajax({

                            url: '{!! url("brand-data") !!}'+"/"+setting_id,

                            headers: { 'X-CSRF-Token' : '<?php echo csrf_token(); ?>' },

                            type: 'GET',

                            success: function(data) {

                                if(typeof data !="undefined")

                                    data.forEach(function($obj){



                                        if(brand_id == $obj.id)

                                            $(brand_select).append("<option selected='selected' value='"+$obj.id+"'>"+$obj.name+"</option>");

                                        else

                                            $(brand_select).append("<option value='"+$obj.id+"'>"+$obj.name+"</option>");



                                    });

                                $(setting_select).blur();

                                $(brand_select).blur();

                            }

                        });

                    }

                },

                fnInitComplete : function() {

                    this.columnFilter({

                        sPlaceHolder: "head:after",

                        aoColumns: [

                            { sSelector: "#marketplace_select", type: "select", values: [<?php echo $setting_str; ?>]},

                            { sSelector: "#brand_select", type: "select", values: [<?php echo $brands_str; ?>]},

                            null

                        ]

                    });

                }

            });





        } );

    </script>



@stop

resources/views/brands/form.blade.php
<?php
/*
 * $old_logo   =   "brand-logo-placeholder.png";
if(!empty($brand['logo']))
    $old_logo   =   $brand['logo'];
*/
$old_logo   =   "";
if(!empty($brand['logo'])){
    $old_logo   =   $brand['logo'];
}
$logo_file=file_exists('assets/users/brands/logos/'.$old_logo);
if($logo_file!=1){
    $logo_file=0;
}
if($old_logo==''){
    $old_logo   =   "brand-logo-placeholder.png";
}
else if($old_logo!='' and $logo_file==1){
    $old_logo   =   $brand['logo'];
}
else if($old_logo!='' and $logo_file==0){
    $old_logo   =   "not-found.png";
}
?>
@extends('main_template')
@section ("title")
    Brand Definition
@stop
@section("content")
@if(isset($brand))
    {!! Form::model($brand, ['route' => ['brands.update', $brand->id], 'method' => 'patch', 'data-parsley-validate' => '', 'enctype' => "multipart/form-data" ]) !!}
@else
    {!! Form::open(['route' => 'brands.store', 'data-parsley-validate' => " ", 'enctype' => "multipart/form-data" ]) !!}
@endif
<div class="row">
    <div class="col-md-6">
        <div class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-3 control-label">Brand Name:</label>
                <div class="col-sm-7">
            {!! Form::text('name', Input::old('name'), ['class' => 'form-control','data-parsley-trigger' => 'change','required' => '']) !!}
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Brand Signature:</label>
                <div class="col-sm-7">
            {!! Form::textarea('signature', Input::old('signature'), [ 'rows' => '5','class' => 'form-control','data-parsley-trigger' => 'change','required' => '']) !!}
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Seller Account:</label>
                <div class="col-sm-7">
             {!! Form::select('setting_id', $marketplace_settings, Input::old('setting_id'), ['id' => 'setting_id', 'class' => 'form-control','data-parsley-trigger' => 'change','required' => '']) !!}
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group"> <img src="<?php echo asset('assets/users/brands/logos/'.$old_logo); ?>" style="width: 150px !important;height: 150px !important" alt=""> </div>
        <div class="form-group">
            <label>Brand Logo:</label>
            <div class="input-group">
                 <input type="text" class="form-control" readonly>
                <span class="input-group-btn"> <span class="btn btn-default btn-file"> Browse&hellip;
                        {!! Form::file('brand_logo', ['class' => 'field']) !!}
                </span> </span> </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 text-center">
        {!! Form::hidden('id',Input::old('id'), ['name' => 'id']) !!}
        {!! Form::submit('Save', ['name' => 'save','class' => 'btn btn-primary','value' => '1']) !!}
        {!! Form::submit('Save &amp; Add New', ['name' => 'save_add','class' => 'btn btn-black']) !!}
    </div>
</div>
{!! Form::close() !!}
@stop

resources/views/brands/index.blade.php
@extends('main_template')

@section ("title")

    Brand List

@stop

@section("right_header")

    <div class="col-sm-6" xmlns="http://www.w3.org/1999/html">

        <div class="add_link">

            <a href="<?php echo url('brands/create'); ?>"><span class="fa fa-plus"></span> Add New</a>

        </div>

    </div>

@stop

@section("content")
    <div class="wrapper-inline-form">

        <div class="row">

            <div class="col-md-4">

                {!! csrf_field() !!}





                <div class="form-group">

                    <div  name="marketplace_select" id="marketplace_select">



                    </div>

                </div>



                <div class="form-group">

                    <?php /*      <label class="col-lg-4 control-label">Status :</label> */ ?>



                </div>

            </div>

        </div>

    </div>
    <div class="row">

        <div class="col-md-12">



            <div class="table-responsive">

                <table class="table table-bordered table-striped" data-ride="datatables" id="server_sisde_dtable">

                    <thead>

                    <tr bgcolor="#f4f4f4">
                        <th>Sr</th>
                        <th>Brand Name</th>

                        <th>Logo</th>

                        <th>Signature</th>

                        <th>Account Name</th>

                        <th>Action</th>

                    </tr>

                    </thead>

                    <tbody>

                    @if(!empty($brands) && is_array($brands))

                        @foreach($brands as $brand)

                            <?php

                            $logo=$brand['logo'];

                            $logo_file=file_exists('assets/users/brands/logos/'.$logo);

                            if($logo_file!=1)

                            $logo_file=0;

                            ?>

                            <tr>

                                <td> {{{ $brand['name'] }}}</td>

                                <td><?php if($logo==''){?><img src='<?php echo asset("assets/users/brands/logos/brand-logo-placeholder.png"); ?>' width='50' height='50' /><?php }else if($logo!='' and $logo_file==1){?> <img src='<?php echo asset("assets/users/brands/logos/".$brand['logo']); ?>' width='50' height='50' /> <?php } else if($logo!='' and $logo_file==0){?><img src='<?php echo asset("assets/users/brands/logos/not-found.png"); ?>' width='50' height='50' /><?php }?></td>

                                <td> {{{ $brand['signature'] }}}</td>

                                <td> {{{ $brand['sellers']['account_name']. "  (".$brand['sellers']['seller_id'].")" }}}</td>

                                <td nowrap>

                                    <a href=" {{{ route('brands.edit',array("id"=>$brand['id'])) }}}"class="btn btn-default"><i class="fa fa-pencil text"></i></a>&nbsp;

                                    <a data-href="{!! route('brands.destroy',array('id'=>$brand['id'])) !!}" class="btn btn-default  confirm_delete"><i class="fa fa-trash-o text"></i></a>



                                </td>



                            </tr>

                        @endforeach

                    @endif

                    </tbody>

                </table>

            </div>

        </div>

    </div>

@stop

@section('additional_js')

    <script>

        $(function() {

            var table   =   $('#server_sisde_dtable').DataTable( {

                "processing": true,

                "serverSide": true,

                "ajax": "<?php echo url("list-brand-data"); ?>",

                'drawCallback':function() {

                    $(".confirm_delete").attr("data-toggle", "modal");
                    $(".confirm_delete").attr("data-target", "#confirm-delete-modal");

                },

                fnInitComplete : function() {

                    this.columnFilter({

                        sPlaceHolder: "head:after",

                        aoColumns: [
                            null,
                            null,
                            null,
                            null,
                            { sSelector: "#marketplace_select", type: "select", values: [<?php echo $setting_str; ?>]},
                            null

                        ]

                    });

                }

            });





        } );

    </script>



@stop

resources/views/brands/products_traking_form.blade.php
@extends('main_template')
@section ("title")
    Product Definition
@stop
@section('content')
    <div class="col-sm-12">
        {!! Form::open(['route' => 'track-product', 'data-parsley-validate' => " ", 'enctype' => "multipart/form-data" ]) !!}
        <div class="form-horizontal">

            <div class="form-group">
                <label class="col-sm-4 control-label">Seller Account:</label>
                <div class="col-sm-4">
                    {!! Form::select('setting_id', $marketplace_settings, Input::old('setting_id'), ['id' => 'setting_id', 'class' => 'form-control chosen_select','data-parsley-trigger' => 'change','required' => '']) !!}
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">ASIN:</label>
                <div class="col-sm-4">
                    {!! Form::text('asin', Input::old('asin'), ['class' => 'form-control']) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    {!! Form::submit('  Save  ', ['name' => 'save','class' => 'btn btn-primary', 'type' => "button"]) !!}
                </div>


            </div>
        </div>



        {!! Form::close() !!} </div>
@stop