app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get("test_queue/{id}",array("uses"=>"TestController@sendReminderEmail"));
//Route::get("local_testing",array("uses"=>"TestController@local_testing"));
//Route::get("just_test",array("uses"=>"TestController@just_test"));
//Route::get("test_multiple_tables",array("uses"=>"TestController@test_multiple_tables"));
Route::get("test_fetch_products",array("uses"=>"TestController@test_fetch_products"));
//Route::get('test_fetch_products',array("uses"=>"TestController@test_fetch_products"));

Route::get("testing",array("uses"=>"TestController@testing"));
Route::get("test-compose-message",array("uses"=>"TestController@test_compose_message"));


Route::match(array("GET","POST"),"user/login",array('uses'=>'UserController@login'));
Route::get("enqueue-fetch-orders",array("uses"=>"JobsController@enqueueFetchOrderJob"));
Route::get("enqueue-send-emails",array("uses"=>"JobsController@enqueueSendEmailsJob"));
Route::get("enqueue-fetch-products",array("uses"=>"JobsController@enqueueFetchProductsJob"));
Route::get("enqueue-fetch-feedbacks",array("uses"=>"JobsController@enqueueFetchFeedbacks"));
Route::get("enqueue-fetch-reviews",array("uses"=>"JobsController@enqueueFetchReviewsAndRatings"));
Route::get("request-orders-reports",array("uses"=>"JobsController@requestOrdersReports"));
Route::get("unsubscribe/{email}",'BlacklistEmailController@unsubscribe');
Route::get("general-message",'BlacklistEmailController@general_message');

//  Route::get("test_feedback",array("uses"=>"TestController@test_feedback"));
//  Route::get("test_brands",array("uses"=>"TestController@assignBrands"));
//Route::get("test_reviews",array("uses"=>"TestController@test_reviews"));





/*
|--------------------------------------------------------------------------
| Basic Authenticated Routes
|--------------------------------------------------------------------------
*/









Route::group(array("middleware"=>'logged_in'),function(){
//

    Route::get("user/choose-setting/{id}",array('uses'=>'UserController@chooseDefaultSetting'));
    Route::get("user/logout",array("uses"=>'UserController@logout'));

    Route::group(array("prefix"=>'opportunityfinder'),function(){
        Route::get('/', array('as'=>'opportunityfinder','uses' => 'OpportunityController@index'));
        Route::match(array('get', 'post'),"find_opportunity",array("as"=>'find_opportunity','uses'=>'OpportunityController@findOpportunity'));
        Route::get("opportunity_ajax",array("as"=>'opportunity_ajax','uses'=>'OpportunityController@opportunityAjax'));
        Route::get("opportunity_cron",array("as"=>'opportunity_cron','uses'=>'OpportunityController@opportunityCron'));
        Route::get("make_asin",array("as"=>'make_asin','uses'=>'OpportunityController@makeAsin'));
        Route::get("populate_products",array("as"=>'populate_products','uses'=>'OpportunityController@populateProducts'));
        Route::get("populate_general_products",array("as"=>'populate_general_products','uses'=>'OpportunityController@populateGeneralProducts'));
        Route::get("get_review_rating",array("as"=>'get_review_rating','uses'=>'OpportunityController@getReviewRating'));
        Route::get("set_price",array("as"=>'set_price','uses'=>'OpportunityController@gePrice'));
        Route::get("saved-search",array('uses'=>'OpportunityController@savedSearch'));
        Route::get("remove_saved_search",array('uses'=>'OpportunityController@removeSavedSearch'));
        Route::match(array('get', 'post'),"scrap_top_sellers",array("as"=>'scrap_top_sellers','uses'=>'OpportunityController@scrap_top_sellers'));
        Route::match(array('get', 'post'),"del_pro",array("as"=>'del_pro','uses'=>'OpportunityController@del_pro'));
    });

    Route::group(array("middleware"=>'check_user_settings'),function()
    {

        Route::get("orders",array("as"=>'orders','uses'=>'BrandController@orders'));

        Route::get("products",array("as"=>"products","uses"=>"UserController@products"));
        Route::get('/',array("uses"=>"UserController@index"));
        Route::resource("brands",'BrandController');
        Route::match(array("GET","POST"),"messages/settings",array("as"=>'settings','uses'=>'MessageController@saveSetting'));
        Route::get("messages/sent",array("as"=>'settings','uses'=>'MessageController@sent'));
        Route::get("messages/outbox",array("as"=>'outbox','uses'=>'MessageController@outbox'));
        Route::get("messages/outbox/delete/{id}",array('uses'=>'MessageController@deleteOutbox'));


        Route::resource("messages",'MessageController');
        Route::resource("variables",'VariableController');
        Route::resource("blacklist-emails",'BlacklistEmailController');


        Route::get("brand-data/{setting_id}",array("uses"=>"BrandController@getBrandData"));
        Route::get("assign-brand",array("uses"=>"BrandController@assignBrands"));
        Route::post("save-brand-assignment",array("uses"=>"BrandController@saveBrandAssignment"));
        Route::match(array("GET","POST"),"product-data",array('as'=>'product-data','uses'=>'BrandController@getProductData'));
        Route::get("feedbacks",array('as'=>'feedbacks','uses'=>'FeedbackController@index'));
        Route::get("feedback-detail/{feedback}",array("as"=>"feedback-detail","uses"=>"FeedbackController@show"));
        Route::match(array("GET","POST"),"feedbacks-data",array('as'=>'feedbacks-data','uses'=>'FeedbackController@getData'));
        Route::post("feedbacks/update/{feedback}",array('as'=>'feedbacks/update','uses'=>'FeedbackController@update'));

        Route::get("track-product",array("as"=>"track-product","uses"=>"BrandController@trackProduct"));
        Route::post("track-product",array("as"=>"track-product","uses"=>"BrandController@trackAndSaveProduct"));
        Route::get("list-brand-data",array("uses"=>"BrandController@getListBrandData"));
        Route::get("list-order-data",array("uses"=>"BrandController@getListOrderData"));
        Route::get("report_testing",array("uses"=>"TestController@report_testing"));
        Route::get("report_list_testing",array("uses"=>"TestController@report_list_testing"));
        Route::get("get_report_testing",array("uses"=>"TestController@get_report_testing"));





        /*
        |--------------------------------------------------------------------------
        | User Routes
        |--------------------------------------------------------------------------
        */
        Route::group(array("prefix"=>"user"),function(){

            Route::get("dashboard",array('uses'=>'UserController@index'));
            Route::get("rating-data",array("as"=>"rating-data","uses"=>"UserController@getProductData"));

            /*
             *  User MarketPlace Setting routes
             */
            Route::get("add-marketplace-setting",array('uses'=>'UserController@saveMarketplaceSetting'));
            Route::get("edit-marketplace-setting/{id}",array('uses'=>'UserController@saveMarketplaceSetting'));
            Route::post("save-marketplace-setting",array('uses'=>'UserController@saveMarketplaceSetting'));
            Route::get("marketplace-settings",array('uses'=>'UserController@marketplaceSettings'));
            Route::get("delete-marketplace-setting/{id}",array('uses'=>'UserController@deleteMarketplaceSetting'));
            /*
             *  User Product Advertising Setting routes
             */
            Route::get("add-aws-setting",array('uses'=>'UserController@saveProdAdvSetting'));
            Route::get("edit-aws-setting/{id}",array('uses'=>'UserController@saveProdAdvSetting'));
            Route::post("save-product-advertising-setting",array('uses'=>'UserController@saveProdAdvSetting'));
            Route::get("aws-settings",array('uses'=>'UserController@prodAdvSettings'));
            Route::get("delete-product-advertising-setting/{id}",array('uses'=>'UserController@deleteProdAdvSetting'));
        });




    });



});

app/Http/Controllers/BlacklistEmailController.php
<?php

namespace App\Http\Controllers;

use App\BlacklistEmail;
use App\UserAmazonSetting;
use App\Http\Requests\BlacklistEmailRequest;
use Illuminate\Support\Facades\Session;
use App\Http\Requests;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Redirect;

class BlacklistEmailController extends Controller
{
    private $amazon_settings;
    private $user;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $user                   =   Session::get('user');
        $amazon_settings        =   UserAmazonSetting::where(array("profile_id"=>$user['profile_id']))->lists("account_name","id");
        $this->user             =   $user;
        if($amazon_settings)
            $amazon_settings    =   $amazon_settings->toArray();
        else
            $amazon_settings    =   array();

        $this->amazon_settings  =   $amazon_settings;
    }
    public function index()
    {
        $blacklist_emails =   BlacklistEmail::getBlacklistEmails($this->user['profile_id']);
        return View::make("blacklistemails.index", array("blacklist_emails"=>$blacklist_emails,"amazon_settings"=>$this->amazon_settings));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make("blacklistemails.form")->with(array("amazon_settings"=>$this->amazon_settings));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlacklistEmailRequest $request)
    {
        $data = \Input::all();
        $data['profile_id'] =   $this->user['profile_id'];

        $result = BlacklistEmail::saveToDb($data);

        if ($result['status'] == '1')
        {
            if(isset($data['save_add']))
                return Redirect::route('blacklist-emails.create')->with('success_message', $result['message']);
            else
                return Redirect::route('blacklist-emails.index')->with('success_message', $result['message']);
        }
        else if ($result['status'] == '3')
        {
            return Redirect::route('blacklist-emails.index')->with('error_message',$result['message']);

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(BlacklistEmail $blacklist_email)
    {
        return View::make("blacklistemails.form", array("blacklist_email"=>$blacklist_email,"amazon_settings"=>$this->amazon_settings));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlacklistEmailRequest $request, $id)
    {
        $data = \Input::all();
        $data['profile_id'] =   $this->user['profile_id'];
        $result           =   BlacklistEmail::saveToDb($data);

        if ($result['status'] == '1')
        {
            if(isset($data['save_add']))
                return Redirect::route('blacklist-emails.create')->with('success_message', $result['message']);
            else
                return Redirect::route('blacklist-emails.index')->with('success_message', $result['message']);
        }
        else if ($result['status'] == '3')
        {
            return Redirect::route('blacklist-emails.index')->with('error_message',$result['message']);

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(BlacklistEmailRequest $request, BlacklistEmail $bl_email)
    {
        $is_deleted =   BlacklistEmail::deleteBlackListEmail($bl_email);
        if ($is_deleted)
        {
            $message    =" Email removed from BlackList of Corresponding Account. ";
            Session::flash("success_message",$message);
        }
        else
        {
            $message    =" Email could not be removed from BlackList of Corresponding Account. ";
            Session::flash("error_message",$message);
        }
        return url("blacklist-emails");
    }

    public function unsubscribe($email)
    {
        if(!empty($email))
        {
            if(filter_var($email,FILTER_VALIDATE_EMAIL))
            {
                $already_unsubscribed   =   BlacklistEmail::where(array("email"=>$email,"setting_id"=>0))->get();
                if(!$already_unsubscribed->isEmpty())
                {
                    return redirect("general-message")->with("error_message","Already Unsubscribed");
                }
                $bl_email               =   new BlacklistEmail();
                $bl_email->email        =   $email;
                $bl_email->created_at   =   date("Y-m-d h:i:s");
                $bl_email->updated_at   =   date("Y-m-d h:i:s");
                $bl_email->setting_id   =   "0";
                $bl_email->save();
                return redirect("general-message")->with("success_message","Successfully Unsubscribed");
            }
            return redirect("general-message")->with("error_message","Invalid email");
        }
        return redirect("general-message")->with("error_message","Invalid request");
    }
    public function general_message()
    {
        echo Session::get("error_message");echo "<br/><br/>";
        echo Session::get("success_message");
    }
}

resources/views/blacklistemails/form.blade.php
@extends('main_template')
@section ("title")
    Blacklist Email Definition
@stop
@section("content")
    @if(isset($blacklist_email))
        {!! Form::model($blacklist_email, ['route' => ['blacklist-emails.update', $blacklist_email->id], 'method' => 'patch', 'data-parsley-validate' => '', 'enctype' => "multipart/form-data" ]) !!}
    @else
        {!! Form::open(['route' => 'blacklist-emails.store', 'data-parsley-validate' => '', 'enctype' => "multipart/form-data" ]) !!}
    @endif
    <div class="row">
        <div class="col-md-6">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-3 control-label">Blacklist Email:</label>
                    <div class="col-sm-7">
                        {!! Form::text('email', Input::old('email'), ['class' => 'form-control','data-parsley-trigger' => 'change','required' => '','data-parsley-type'=>'email']) !!}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Account Name:</label>
                    <div class="col-sm-7">
                        {!! Form::select('setting_id', $amazon_settings, Input::old('setting_id'), ['id' => 'setting_id', 'class' => 'form-control chosen_select','data-parsley-trigger' => 'change','required' => '']) !!}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Blacklist Email:</label>
                    <div class="col-sm-7">
                        {!! Form::hidden('id',Input::old('id'), ['name' => 'id']) !!}
                        {!! Form::submit('Save', ['name' => 'save','class' => 'btn btn-primary']) !!}
                        {!! Form::submit('Save &amp; Add New', ['name' => 'save_add','class' => 'btn btn-black']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {!! Form::close() !!}
@stop

resources/views/blacklistemails/index.blade.php
<?php
        $i=1;
?>
@extends('main_template')
@section ("title")
    BlacklistEmails List
@stop
@section("right_header")
    <div class="col-sm-6" xmlns="http://www.w3.org/1999/html">
        <div class="add_link">
            <a href="<?php echo url('blacklist-emails/create'); ?>"><span class="fa fa-plus"></span> Add New</a>
        </div>
    </div>
@stop
@section("content")
    <div class="row">
        <div class="col-md-12">

            <div class="table-responsive">
                <table class="table table-bordered table-striped data_table" data-ride="datatables">
                    <thead>
                    <tr bgcolor="#f4f4f4">
                        <th width="10%">Sr</th>
                        <th width="30%">Email</th>
                        <th width="30%">Account Name</th>
                        <th width="30%">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($blacklist_emails) && is_array($blacklist_emails))
                        @foreach($blacklist_emails as $blacklist_email)
                            <tr>
                                <td> {!! $i++ !!}</td>
                                <td> {{{ $blacklist_email['email'] }}}</td>
                                <td> {{{ $blacklist_email['settings']['account_name'] }}}</td>
                                <td nowrap>
                                    <a href=" {{{ route('blacklist-emails.edit',array("id"=>$blacklist_email['id'])) }}}"class="btn btn-default"><i class="fa fa-pencil text"></i></a>&nbsp;
                                    <a data-href="{!! route('blacklist-emails.destroy',array('id'=>$blacklist_email['id'])) !!}" class="btn btn-default  confirm_delete"><i class="fa fa-trash-o text"></i></a>

                                </td>

                            </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop